### ISSUE TITLE
Update method for `fwspp` object

### ISSUE THREAD

**Issue by adamdsmith** [USFWS/fwspp#3]
Store as an attribute the datetime a query was initiated.  Subsequently use this to pass to the `get_*` functions to, I suspect, *profoundly* reduce the size and increase the speed of query updates.

- [ ] [GBIF API accepts a `lastInterpreted` parameter](https://www.gbif.org/developer/occurrence#p_lastInterpreted)
- [x] [No obvious solution in BISON SOLR API](https://bison.usgs.gov/doc/api.jsp#solr)
- [ ] [Maybe `datemodified` in iDigBio API, but need to check further](https://github.com/idigbio/idigbio-search-api/wiki/Index-Fields#record-query-fields)
- [ ] [Perhaps `lastindexed` is appropriate VertNet parameter](https://github.com/VertNet/webapp/wiki/The-API-search-function)?
- [ ] [No obvious EcoEngine solution](https://ecoengine.berkeley.edu/docs/quickstart.html#search), but probably not a huge concern
- [ ] [No obvious AntWeb solution](https://www.antweb.org/api/v2/), but likely not a concern

**Comment by mccrea-cobb** [comment]
No longer needed for BISON.
