### ISSUE TITLE
sf (1.0-13) and s2 (1.1.4) update causing error in install_fws_cadastral function

### ISSUE THREAD

**Issue by timothymfox** [USFWS/fwspp#38]
After updating sf  and s2 the following error is returned when running install_fws_cadastral:
USFWS Cadastral Database downloaded and installed successfully.
Spherical geometry (s2) switched off
Storing USFWS cadastral geodatabase in a more efficient format. This will take several additional
minutes.
Processing USFWS Interest boundaries.
Error in scan(text = lst[[length(lst)]], quiet = TRUE) : 
  scan() expected 'a real', got 'ParseException:'
Error in (function (msg)  : ParseException: Unknown WKB type 12
The legacy packages maptools, rgdal, and rgeos, underpinning this package
will retire shortly. Please refer to R-spatial evolution reports on
https://r-spatial.org/r/2023/05/15/evolution4.html for details.
This package is now running under evolution status 0

**Comment by mccrea-cobb** [comment]
This was related to https://github.com/r-spatial/sf/issues/427. Resolved by replacing st_cast(MUTLIPOLYGON) with custom function to ensure multipolygons https://github.com/r-spatial/sf/issues/427#issuecomment-874476218. See commit cb0aa4f8966a24e344a72e27541a43f82cbf2c46
