### ISSUE TITLE
Add species evidence links from ServCat

### ISSUE THREAD

**Issue by mccrea-cobb** [USFWS/fwspp#39]
Add function to:
- query ServCat records for a refuge and record species occurrences
- clean taxonomy of species occurrence records from ServCat

**Comment by timothymfox** [comment]
functionality added to fws_occ function to pull occurrence records from ServCat
cd532ca93aeedf13e29cbd12b2172aa37da03216
18dbec07c6f5a759831eb88d9abe71812ba57c99
9735c5517d4d44943ad00a41e62d413d7e49c5d3
d55362e437dc45261dd82872fcfdde4e4899f09d
f081255eb201740d309b993ba3c74f617f9bc358
6e34b99729a51e4531e5cc5225285c5e0e2f050a
2c80b9b86c5b515ef1b13d3f0af9ce1c35e30518
19719ed9bb0e1c3639d21744031e349a6c87f2df
b250400759a927c1fb8eb7abf4754656b287dce0
e5bff467ea21e0afe4bca008c704bbd7b6f8237a
